
CREATE TABLE User (
    id INT AUTO_INCREMENT NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    active TINYINT(1) DEFAULT 1,
    PRIMARY KEY (id)
);
